application: cultureplexstatus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
